[package]
name = "my_tui_app"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
crossterm = { version = "0.28.0", features = ["event-stream"] }
serde_json = "1.0"
